on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/create-swarmion-app/**'
      - 'examples/**'
      - 'scripts/check-examples.sh'

# cancel previous runs on the same PR
concurrency:
  group: ${{ github.ref }}/check-examples
  cancel-in-progress: true

name: 🔍 PR Check examples

env:
  CI: true
  NODE_VERSION: 16

defaults:
  run:
    shell: bash

jobs:
  check-examples:
    name: 🔍 Check examples
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install & cache node dependencies
        uses: ./.github/actions/install-node-deps
      - name: '🔍 Check examples'
        run: REF=${{ github.event.pull_request.head.sha }} sh ./scripts/check-examples.sh
